#!/bin/sh
# This script is only used for developement. It is removed by the 
# distribution process. 

set -e

OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -tag debug -classic-display \
                          -use-ocamlfind"}

action () 
{
    case $1 in
      default)      $OCAMLBUILD webglue.native ;;
      tests)        $OCAMLBUILD test.native ;;
      formats)      $OCAMLBUILD formats-native.otarget ;;
      api-doc)      shift; pkg-doc $* doc/api.docdir ;;
      configure)    shift; pkg/configure $* ;;
      clean)        $OCAMLBUILD -clean ;;
      *)            $OCAMLBUILD $* ;;
    esac
} 

if [ $# -eq 0 ]; 
then action default ; 
else action $*; fi
