#!/bin/sh

## Usage: pkg-opam-install
## Generate an .install file for opam

set -e
LOC=`dirname $0`

. $LOC/pkg-info

I="webglue.install"

## TODO be more smart...

$CAT > $I <<EOF
bin: [ "_build/src/tool/webglue.native" { "webglue" } ]
lib: [ "src/api/META"
       "_build/src/api/wg.mli"
       "_build/src/api/wg.cmi"
       "_build/src/api/wg.cma"
       "_build/src/api/wg.cmx"
       "_build/src/api/wg.cmxa"
       "_build/src/api/wg.cmxs"
       "_build/src/formats/w_css.cmxs"
       "_build/src/formats/w_text.cmxs"
       "_build/src/formats/w_files.cmxs"
       "_build/src/formats/w_timestamp.cmxs"
       "_build/src/formats/w_sitemap.cmxs"    
       "_build/src/formats/w_xml.cmxs" ]
doc: [ "README.md" "CHANGES.md" ]
EOF
