#!/bin/sh

## Usage: pkg-opam-install
## Generate an .install file for opam

set -e
LOC=`dirname $0`

. $LOC/pkg-info

I="webglue.install"

echo "bin: [ \"_build/src/tool/webglue.native\" { \"webglue\" } ]" >> $I

