#!/bin/sh

# Usage: pkg-configure LIBDIR 
# Configures the package LIBDIR should be the location of format
# plugin installs.

set -e
LOC=`dirname $0`

ECHO=${ECHO:="echo"}

. $LOC/pkg.config

$ECHO "let value = \"$1/webglue\"" > src/tool/libdir.ml ;;
